import {
  // Fashion & Apparel
  Shirt,
  Footprints,
  Handbag,
  ShoppingBag,
  Briefcase,
  BaggageClaim,
  Glasses,
  Watch,
  Crown,
  Gem,
  Sparkles,
  Scissors,
  Umbrella,
  Baby,
  Feather,
  Tag,
  Clock,

  // Gastro & Food
  Coffee,
  Utensils,
  UtensilsCrossed,
  Beer,
  Wine,
  Pizza,
  Apple,
  Cake,
  IceCream,
  Sandwich,
  Soup,
  Cookie,
  Milk,
  Croissant,
  CupSoda,
  Martini,
  Candy,
  Salad,
  Beef,
  Fish,
  Egg,

  // Home & Services
  Home,
  Armchair,
  BookOpen,
  Paintbrush,
  Flower2,
  Bed,
  Bath,
  Droplets,
  Droplet,
  Brush,
  Heart,
  Key,
  Hammer,
  Flame,
  Lightbulb,
  Compass,
  MapPin,
  Car,
  Bike,
  Music,

  // Tech & Tools
  Smartphone,
  Laptop,
  Tv,
  Headphones,
  Gamepad2,
  Camera,
  Printer,
  Wrench,
  Battery,
  Cpu,
  Wifi,
  Plug,
  Radio,

  // Retail & Symbols
  ShoppingBasket,
  Gift,
  Package,
  Boxes,
  Percent,
  BadgePercent,
  Coins,
  Ticket,
  CreditCard,
  Wallet,
  Receipt,
  QrCode,
  Barcode,
  ScanLine,
  Sun,
  Moon,
  Zap,
  ShieldCheck,
  Award,
  Star,
  Smile,
  Bell,
  Truck,
  DollarSign,
  PiggyBank,
  Layers,
  Inbox,
  FileText,
  HelpCircle
} from 'lucide-react';

export const PRESET_ICON_MAP = {
  // Fashion & Apparel
  Shirt,
  Footprints,
  Handbag,
  ShoppingBag,
  Briefcase,
  BaggageClaim,
  Glasses,
  Watch,
  Crown,
  Gem,
  Sparkles,
  Scissors,
  Umbrella,
  Baby,
  Feather,
  Tag,
  Clock,

  // Gastro & Food
  Coffee,
  Utensils,
  UtensilsCrossed,
  Beer,
  Wine,
  Pizza,
  Apple,
  Cake,
  IceCream,
  Sandwich,
  Soup,
  Cookie,
  Milk,
  Croissant,
  CupSoda,
  Martini,
  Candy,
  Salad,
  Beef,
  Fish,
  Egg,

  // Home & Services
  Home,
  Armchair,
  BookOpen,
  Paintbrush,
  Flower2,
  Bed,
  Bath,
  Droplets,
  Droplet,
  Brush,
  Heart,
  Key,
  Hammer,
  Flame,
  Lightbulb,
  Compass,
  MapPin,
  Car,
  Bike,
  Music,

  // Tech & Tools
  Smartphone,
  Laptop,
  Tv,
  Headphones,
  Gamepad2,
  Camera,
  Printer,
  Wrench,
  Battery,
  Cpu,
  Wifi,
  Plug,
  Radio,

  // Retail & Symbols
  ShoppingBasket,
  Gift,
  Package,
  Boxes,
  Percent,
  BadgePercent,
  Coins,
  Ticket,
  CreditCard,
  Wallet,
  Receipt,
  QrCode,
  Barcode,
  ScanLine,
  Sun,
  Moon,
  Zap,
  ShieldCheck,
  Award,
  Star,
  Smile,
  Bell,
  Truck,
  DollarSign,
  PiggyBank,
  Layers,
  Inbox,
  FileText,
  HelpCircle
};

export const PRESET_ICON_CATEGORIES = [
  { id: 'all', labelKey: 'presets.all_icons', fallback: 'Všechny' },
  { id: 'fashion', labelKey: 'presets.cat_fashion', fallback: 'Móda & Textil' },
  { id: 'gastro', labelKey: 'presets.cat_gastro', fallback: 'Gastro & Nápoje' },
  { id: 'home', labelKey: 'presets.cat_home', fallback: 'Domov & Služby' },
  { id: 'tech', labelKey: 'presets.cat_tech', fallback: 'Technika & Nástroje' },
  { id: 'symbols', labelKey: 'presets.cat_symbols', fallback: 'Symboly & Slevy' }
];

export const ICON_CATEGORY_MAP = {
  // Fashion
  Shirt: 'fashion',
  Footprints: 'fashion',
  Handbag: 'fashion',
  ShoppingBag: 'fashion',
  Briefcase: 'fashion',
  BaggageClaim: 'fashion',
  Glasses: 'fashion',
  Watch: 'fashion',
  Crown: 'fashion',
  Gem: 'fashion',
  Sparkles: 'fashion',
  Scissors: 'fashion',
  Umbrella: 'fashion',
  Baby: 'fashion',
  Feather: 'fashion',
  Tag: 'fashion',
  Clock: 'fashion',

  // Gastro
  Coffee: 'gastro',
  Utensils: 'gastro',
  UtensilsCrossed: 'gastro',
  Beer: 'gastro',
  Wine: 'gastro',
  Pizza: 'gastro',
  Apple: 'gastro',
  Cake: 'gastro',
  IceCream: 'gastro',
  Sandwich: 'gastro',
  Soup: 'gastro',
  Cookie: 'gastro',
  Milk: 'gastro',
  Croissant: 'gastro',
  CupSoda: 'gastro',
  Martini: 'gastro',
  Candy: 'gastro',
  Salad: 'gastro',
  Beef: 'gastro',
  Fish: 'gastro',
  Egg: 'gastro',

  // Home
  Home: 'home',
  Armchair: 'home',
  BookOpen: 'home',
  Paintbrush: 'home',
  Flower2: 'home',
  Bed: 'home',
  Bath: 'home',
  Droplets: 'home',
  Droplet: 'home',
  Brush: 'home',
  Heart: 'home',
  Key: 'home',
  Hammer: 'home',
  Flame: 'home',
  Lightbulb: 'home',
  Compass: 'home',
  MapPin: 'home',
  Car: 'home',
  Bike: 'home',
  Music: 'home',

  // Tech
  Smartphone: 'tech',
  Laptop: 'tech',
  Tv: 'tech',
  Headphones: 'tech',
  Gamepad2: 'tech',
  Camera: 'tech',
  Printer: 'tech',
  Wrench: 'tech',
  Battery: 'tech',
  Cpu: 'tech',
  Wifi: 'tech',
  Plug: 'tech',
  Radio: 'tech',

  // Symbols
  ShoppingBasket: 'symbols',
  Gift: 'symbols',
  Package: 'symbols',
  Boxes: 'symbols',
  Percent: 'symbols',
  BadgePercent: 'symbols',
  Coins: 'symbols',
  Ticket: 'symbols',
  CreditCard: 'symbols',
  Wallet: 'symbols',
  Receipt: 'symbols',
  QrCode: 'symbols',
  Barcode: 'symbols',
  ScanLine: 'symbols',
  Sun: 'symbols',
  Moon: 'symbols',
  Zap: 'symbols',
  ShieldCheck: 'symbols',
  Award: 'symbols',
  Star: 'symbols',
  Smile: 'symbols',
  Bell: 'symbols',
  Truck: 'symbols',
  DollarSign: 'symbols',
  PiggyBank: 'symbols',
  Layers: 'symbols',
  Inbox: 'symbols',
  FileText: 'symbols',
  HelpCircle: 'symbols'
};

export const PRESET_ICON_LABELS = {
  Shirt: 'Oblečení / Tričko / Móda / Shirt',
  Footprints: 'Obuv / Boty / Tenisky / Shoes',
  Handbag: 'Kabelka / Taška / Handbag',
  ShoppingBag: 'Nákupní taška / Bag',
  Briefcase: 'Kufřík / Aktovka / Briefcase',
  BaggageClaim: 'Zavazadla / Kufr / Luggage',
  Glasses: 'Brýle / Optika / Glasses',
  Watch: 'Hodinky / Šperky / Watch',
  Crown: 'Luxus / Prémium / Koruna / Crown',
  Gem: 'Klenoty / Šperky / Diamant / Gem',
  Sparkles: 'Módní doplňky / Třpyt / Sparkles',
  Scissors: 'Krejčovství / Nůžky / Scissors',
  Umbrella: 'Deštník / Doplňky / Umbrella',
  Baby: 'Kojenecké / Dětské zboží / Baby',
  Feather: 'Hedvábí / Peří / Jemný textil / Feather',
  Tag: 'Cenovka / Štítek / Značka / Tag',
  Clock: 'Čas / Hodiny / Služba na hodinu / Clock',

  Coffee: 'Káva / Espresso / Čaj / Nápoj / Coffee',
  Utensils: 'Jídlo / Příbory / Menu / Restaurant',
  UtensilsCrossed: 'Restaurace / Oběd / Večeře / Food',
  Beer: 'Pivo / Čepované / Pub / Beer',
  Wine: 'Víno / Sklenka / Vinotéka / Wine',
  Pizza: 'Pizza / Fast food / Bistro',
  Apple: 'Ovoce / Zelenina / Zdravá výživa / Apple',
  Cake: 'Dort / Zákusek / Cukrárna / Cake',
  IceCream: 'Zmrzlina / Nanuk / Dezert / Ice Cream',
  Sandwich: 'Sendvič / Bageta / Toast / Sandwich',
  Soup: 'Polévka / Teplé jídlo / Bowl',
  Cookie: 'Sušenka / Pečivo / Cookie',
  Milk: 'Mléko / Mléčné výrobky / Milk',
  Croissant: 'Croissant / Pekárna / Pečivo',
  CupSoda: 'Limonáda / Soda / Nealko nápoj / Drink',
  Martini: 'Koktejl / Bar / Alkohol / Martini',
  Candy: 'Sladkosti / Bonbóny / Cukrovinky / Candy',
  Salad: 'Salát / Zelenina / Čerstvé / Salad',
  Beef: 'Maso / Hovězí / Steak / Řeznictví / Meat',
  Fish: 'Ryba / Mořské plody / Fish',
  Egg: 'Vejce / Snídaně / Suroviny / Egg',

  Home: 'Domov / Bydlení / Domácnost / Home',
  Armchair: 'Nábytek / Křeslo / Pohodlí / Furniture',
  BookOpen: 'Knihy / Časopisy / Tisk / Book',
  Paintbrush: 'Malování / Barvy / Hobby / Paint',
  Flower2: 'Květiny / Zahrada / Vazba / Flower',
  Bed: 'Ložní prádlo / Ubytování / Nocleh / Bed',
  Bath: 'Koupelna / Drogerie / Vana / Bath',
  Droplets: 'Šampon / Kosmetika / Voda / Droplets',
  Droplet: 'Olej / Parfém / Kapka / Droplet',
  Brush: 'Kartáč / Péče / Kosmetika / Brush',
  Heart: 'Zdraví / Péče / Láska / Drogerie / Heart',
  Key: 'Klíče / Zámky / Bezpečnost / Key',
  Hammer: 'Kladivo / Stavba / Řemeslo / Hammer',
  Flame: 'Svíčky / Oheň / Teplo / Flame',
  Lightbulb: 'Osvětlení / Žárovka / Nápad / Lamp',
  Compass: 'Outdoor / Turistika / Kompas / Compass',
  MapPin: 'Lokalita / Místo / Doprava / Map',
  Car: 'Auto / Garáž / Autodoplňky / Car',
  Bike: 'Kolo / Cyklistika / Sport / Bike',
  Music: 'Hudba / Zvuk / Audio / CD / Music',

  Smartphone: 'Mobil / Smartphone / Telefon',
  Laptop: 'Notebook / Počítač / IT / Laptop',
  Tv: 'Televize / Displej / TV',
  Headphones: 'Sluchátka / Audio / Zvuk / Sound',
  Gamepad2: 'Hry / Herní konzole / Hračky / Game',
  Camera: 'Fotoaparát / Foto / Kamera / Camera',
  Printer: 'Tiskárna / Kancelář / Papír / Print',
  Wrench: 'Nářadí / Servis / Oprava / Klíč / Tool',
  Battery: 'Baterie / Nabíjení / Akumulátor / Battery',
  Cpu: 'Elektronika / Čip / Komponenty / Hardware',
  Wifi: 'Internet / Připojení / Síť / Wifi',
  Plug: 'Kabel / Nabíječka / Zásuvka / Adaptér / Plug',
  Radio: 'Rádio / Přijímač / Zvuk / Radio',

  ShoppingBasket: 'Košík / Nákup / Basket',
  Gift: 'Dárek / Dárkový poukaz / Balení / Gift',
  Package: 'Balík / Zásilka / Balení / Package',
  Boxes: 'Sklad / Krabice / Karton / Boxes',
  Percent: 'Sleva / Procento / Akce / Percent',
  BadgePercent: 'Akční nabídka / Výprodej / Sale',
  Coins: 'Záloha / Mince / Vratné lahve / Coins',
  Ticket: 'Vstupenka / Lístek / Kupón / Ticket',
  CreditCard: 'Platba / Karta / Banka / Card',
  Wallet: 'Peněženka / Hotovost / Wallet',
  Receipt: 'Účtenka / Doklad / Paragon / Receipt',
  QrCode: 'QR Kód / Odkaz / Platba / QR',
  Barcode: 'Čárový kód / EAN / Barcode',
  ScanLine: 'Skenování / Čtečka / Scan',
  Sun: 'Léto / Sezóna / Slunce / Sun',
  Moon: 'Noc / Noční prodej / Večer / Moon',
  Zap: 'Blesk / Rychlý prodej / Expres / Zap',
  ShieldCheck: 'Záruka / Pojištění / Ověřeno / Shield',
  Award: 'Ocenění / Prémium / Medaile / Award',
  Star: 'Hvězda / Oblíbené / Tip / Star',
  Smile: 'Děti / Úsměv / Zábava / Smile',
  Bell: 'Upozornění / Zvonek / Služba / Bell',
  Truck: 'Doprava / Dovoz / Kurýr / Delivery',
  DollarSign: 'Měna / Finance / Poplatek / Money',
  PiggyBank: 'Pokladnička / Spoření / Slevový bonus / Piggy',
  Layers: 'Vrstvy / Sortiment / Katalog / Layers',
  Inbox: 'Příjem / Zboží / Schránka / Inbox',
  FileText: 'Smlouva / Formulář / Dokument / File',
  HelpCircle: 'Ostatní / Různé / Nápověda / Other'
};

export function getPresetIconComponent(iconKey) {
  if (!iconKey || !PRESET_ICON_MAP[iconKey]) return null;
  return PRESET_ICON_MAP[iconKey];
}
