import {
  Shirt,
  Footprints,
  ShoppingBag,
  Gift,
  Package,
  Sparkles,
  Coffee,
  Utensils,
  Smartphone,
  Tag,
  Glasses,
  Home,
  Shield,
  Car,
  Smile,
  Heart,
  Scissors,
  Wrench,
  Layers,
  Star,
  HelpCircle,
  Percent,
  Award,
  Crown,
  Watch,
  Beer,
  Wine,
  Pizza,
  Apple,
  Cake,
  IceCream,
  Laptop,
  Tv,
  Headphones,
  Gamepad2,
  Paintbrush,
  Flower2,
  Bed,
  Ticket,
  CreditCard,
  Sun,
  Zap,
  Coins,
  BadgePercent,
  ShieldCheck,
  ShoppingBasket,
  Armchair,
  BookOpen
} from 'lucide-react';

export const PRESET_ICON_MAP = {
  Shirt,
  Footprints,
  ShoppingBag,
  ShoppingBasket,
  Gift,
  Package,
  Sparkles,
  Crown,
  Watch,
  Glasses,
  Coffee,
  Utensils,
  Beer,
  Wine,
  Pizza,
  Apple,
  Cake,
  IceCream,
  Smartphone,
  Laptop,
  Tv,
  Headphones,
  Gamepad2,
  Home,
  Armchair,
  BookOpen,
  Paintbrush,
  Flower2,
  Bed,
  Scissors,
  Wrench,
  Heart,
  Tag,
  Car,
  Smile,
  Star,
  Percent,
  BadgePercent,
  Coins,
  Ticket,
  CreditCard,
  Sun,
  Zap,
  ShieldCheck,
  Award,
  HelpCircle
};

export const PRESET_ICON_LABELS = {
  Shirt: 'Oblečení / Móda',
  Footprints: 'Obuv / Boty',
  ShoppingBag: 'Tašky / Kabelky',
  ShoppingBasket: 'Nákupní Košík',
  Gift: 'Dárkový Poukaz',
  Package: 'Volný Prodej / Balík',
  Sparkles: 'Šperky / Bižuterie',
  Crown: 'Prémiová Móda / Luxus',
  Watch: 'Hodinky / Šperky',
  Glasses: 'Optika / Sluneční brýle',
  Coffee: 'Káva / Teplé nápoje',
  Utensils: 'Gastronomie / Jídlo',
  Beer: 'Pivo / Alkohol',
  Wine: 'Víno / Vinotéka',
  Pizza: 'Pizza / Rychlé občerstvení',
  Apple: 'Ovoce / Zelenina / Potraviny',
  Cake: 'Cukrárna / Dezerty',
  IceCream: 'Zmrzlina / Sladkosti',
  Smartphone: 'Mobily / Příslušenství',
  Laptop: 'Počítače / IT',
  Tv: 'Elektronika / TV',
  Headphones: 'Audio / Sluchátka',
  Gamepad2: 'Hry / Hračky',
  Home: 'Domácí Potřeby',
  Armchair: 'Nábytek / Bydlení',
  BookOpen: 'Knihy / Tisk',
  Paintbrush: 'Malování / Hobby',
  Flower2: 'Květiny / Zahrada',
  Bed: 'Ubytování / Nocleh',
  Scissors: 'Krejčovství / Služby',
  Wrench: 'Nářadí / Servis & Opravy',
  Heart: 'Kosmetika / Drogerie',
  Tag: 'Cenovka / Štítek',
  Car: 'Auto-Moto / Garáž',
  Smile: 'Dětský Sortiment',
  Star: 'Oblíbené / Speciál',
  Percent: 'Sleva / Akční Zboží',
  BadgePercent: 'Mimořádná Nabídka',
  Coins: 'Vratné Obaly / Zálohy',
  Ticket: 'Vstupenky / Lístky',
  CreditCard: 'Platební Karty / Služba',
  Sun: 'Sezónní Výprodej',
  Zap: 'Rychlá Položka',
  ShieldCheck: 'Záruka / Pojištění',
  Award: 'Prémiová Kvalita',
  HelpCircle: 'Různé / Ostatní'
};

export function getPresetIconComponent(iconKey) {
  if (!iconKey || !PRESET_ICON_MAP[iconKey]) return null;
  return PRESET_ICON_MAP[iconKey];
}
