import {
  Shirt,
  Footprints,
  ShoppingBag,
  Handbag,
  Briefcase,
  BaggageClaim,
  Gift,
  Package,
  Sparkles,
  Crown,
  Gem,
  HatGlasses,
  Glasses,
  Watch,
  Feather,
  Bath,
  Droplets,
  Droplet,
  Brush,
  Heart,
  Coffee,
  Utensils,
  Beer,
  Wine,
  Pizza,
  Apple,
  Cake,
  IceCream,
  Smartphone,
  Laptop,
  Tv,
  Headphones,
  Gamepad2,
  Home,
  Armchair,
  BookOpen,
  Paintbrush,
  Flower2,
  Bed,
  Scissors,
  Wrench,
  Tag,
  Car,
  Smile,
  Star,
  Percent,
  BadgePercent,
  Coins,
  Ticket,
  CreditCard,
  Sun,
  Zap,
  ShieldCheck,
  Award,
  HelpCircle,
  ShoppingBasket
} from 'lucide-react';

export const PRESET_ICON_MAP = {
  Shirt,
  Footprints,
  Handbag,
  ShoppingBag,
  Briefcase,
  BaggageClaim,
  HatGlasses,
  Glasses,
  Watch,
  Crown,
  Gem,
  Sparkles,
  Feather,
  Bath,
  Droplets,
  Droplet,
  Brush,
  Heart,
  ShoppingBasket,
  Gift,
  Package,
  Coffee,
  Utensils,
  Beer,
  Wine,
  Pizza,
  Apple,
  Cake,
  IceCream,
  Smartphone,
  Laptop,
  Tv,
  Headphones,
  Gamepad2,
  Home,
  Armchair,
  BookOpen,
  Paintbrush,
  Flower2,
  Bed,
  Scissors,
  Wrench,
  Tag,
  Car,
  Smile,
  Star,
  Percent,
  BadgePercent,
  Coins,
  Ticket,
  CreditCard,
  Sun,
  Zap,
  ShieldCheck,
  Award,
  HelpCircle
};

export const PRESET_ICON_LABELS = {
  Shirt: 'Oblečení / Móda',
  Footprints: 'Obuv / Boty & Tenisky',
  Handbag: 'Kabelky & Tašky',
  ShoppingBag: 'Nákupní Tašky',
  Briefcase: 'Kufříky & Aktovky',
  BaggageClaim: 'Zavazadla & Kufry',
  HatGlasses: 'Klobouky, Čepice & Sluneční brýle',
  Glasses: 'Optika & Módní brýle',
  Watch: 'Hodinky & Náramky',
  Crown: 'Prémiová Móda & Luxus',
  Gem: 'Šperky & Drahokamy',
  Sparkles: 'Módní Doplňky & Bižuterie',
  Feather: 'Jemný Textil, Hedvábí & Peří',
  Bath: 'Šampon, Sprcha & Koupel',
  Droplets: 'Vlasová Kosmetika & Šampon',
  Droplet: 'Sprchové Gely & Oleje',
  Brush: 'Kosmetické Štětce & Péče o Boty',
  Heart: 'Drogerie & Pleťová Kosmetika',
  ShoppingBasket: 'Nákupní Košík',
  Gift: 'Dárkový Poukaz',
  Package: 'Volný Prodej / Balík',
  Coffee: 'Káva / Teplé nápoje',
  Utensils: 'Gastronomie / Jídlo',
  Beer: 'Pivo / Alkohol',
  Wine: 'Víno / Vinotéka',
  Pizza: 'Pizza / Fast Food',
  Apple: 'Ovoce, Zelenina & Potraviny',
  Cake: 'Cukrárna & Dezerty',
  IceCream: 'Zmrzlina & Sladkosti',
  Smartphone: 'Mobily & Příslušenství',
  Laptop: 'Počítače & IT',
  Tv: 'Elektronika & TV',
  Headphones: 'Audio & Sluchátka',
  Gamepad2: 'Hry & Hračky',
  Home: 'Domácí Potřeby',
  Armchair: 'Nábytek & Bydlení',
  BookOpen: 'Knihy & Tisk',
  Paintbrush: 'Malování & Hobby',
  Flower2: 'Květiny & Zahrada',
  Bed: 'Ubytování & Nocleh',
  Scissors: 'Krejčovství & Opravy Oděvů',
  Wrench: 'Nářadí & Servis',
  Tag: 'Cenovka / Štítek',
  Car: 'Auto-Moto & Garáž',
  Smile: 'Dětský Sortiment',
  Star: 'Oblíbené & Speciál',
  Percent: 'Sleva & Akční Zboží',
  BadgePercent: 'Mimořádná Nabídka',
  Coins: 'Vratné Obaly & Zálohy',
  Ticket: 'Vstupenky & Lístky',
  CreditCard: 'Platební Karty / Služba',
  Sun: 'Sezónní Výprodej',
  Zap: 'Expres Položka',
  ShieldCheck: 'Záruka & Pojištění',
  Award: 'Prémiová Kvalita',
  HelpCircle: 'Různé / Ostatní'
};

export function getPresetIconComponent(iconKey) {
  if (!iconKey || !PRESET_ICON_MAP[iconKey]) return null;
  return PRESET_ICON_MAP[iconKey];
}
